#!/bin/bash

# test: Test debops-contrib.influxdb
# Copyright (C) 2017 Patryk Ściborek <patryk@sciborek.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins

ansible-galaxy install -f debops.pki
ansible-galaxy install -f git+https://github.com/debops-contrib/ansible-influxdb_server.git

assert_playbook_check_runs
assert_playbook_idempotent


# Check if correct timezone is set
assert_docs
