#!/bin/bash

# test: Test debops-contrib.influxdb_server
# Copyright (C) 2017 Patryk Ściborek <patryk@sciborek.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"

echo "DEBUG - start ================================="
pwd

find ..

mkdir -p "travis/tests/ansible-mosquitto/inventory/group_vars/debops_service_mosquitto"

cat > travis/tests/ansible-mosquitto/inventory/group_vars/debops_service_mosquitto/mosquitto.yml <<EOF
---

mosquitto__upstream: ${MOSQUITTO_UPSTREAM:-False}

EOF

echo "===="

find .

cat travis/tests/ansible-mosquitto/inventory/group_vars/debops_service_mosquitto/mosquitto.yml

echo "DEBUG - stop  ================================="
install_ansible ${test_ansible_version}
ansible_plugins


assert_playbook_check_runs
assert_playbook_idempotent


assert_running "mosquitto"
# Todo:
#assert_docs
