---

postgresql__dependent_roles:

  - role: 'travis_test'
    flags: [ 'NOLOGIN' ]

  - role: 'travis'

postgresql__dependent_groups:

  - roles: [ 'travis' ]
    groups: [ 'travis_test' ]
    database: 'travis_test'

postgresql__dependent_databases:

  - name: 'travis_test'
    owner: 'travis_test'

postgresql__extensions:

  - database: 'travis_test'
    extension: 'pg_trgm'

postgresql__dependent_pgpass:

  - owner: 'travis'


