#!/bin/bash

# test: Test debops-contrib.influxdb_server
# Copyright (C) 2017 Patryk Ściborek <patryk@sciborek.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


assert_playbook_check_runs
assert_playbook_idempotent


assert_running "influxd"
assert_docs
